kind: Deployment
apiVersion: apps/v1
metadata:
  name: website
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      name: website
      labels:
        app: website
        role: frontend
    spec:
      containers:
      - name: website
        image: registry.digitalocean.com/automait/website:{{CI_BUILD_REF_SLUG}}
        imagePullPolicy: Always
        ports:
        - name: frontend
          containerPort: 80
        resources:
          limits:
            cpu: 1
            memory: 1024Mi
          requests:
            cpu: 0.2
            memory: 64Mi

      restartPolicy: Always
